project:
  type: website
  render:
    - '*.qmd'

profile:
  group: [fr, en]
  default: fr

website:
  site-url: https://inseefrlab.github.io/formation-s3-initiation/
  repo-url: https://github.com/InseeFrLab/formation-s3-initiation.git
#  favicon: img/logo.svg

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
    execute:
      echo: true
      eval: true
      output: true
      warning: true
      error: true
