project:
  output-dir: _site/en

website:
  title: "S3 training course"
  sidebar:
    style: 'docked'
    contents:
      - section: "Fundamentals"
        contents: 
          - text: "Basic types and variables"
            href: source/fundamentals/tutorial.qmd
