::: {.content-visible when-profile="fr"}
# S3 Les Fondamentaux 

## S3 : Une API HTTP

S3 est une API REST HTTP. Des requêtes HTTP sont utilisées pour obtenir, ajouter, envoyer et supprimer des données. 
Afin de communiquer avec l'api nous devrons donc disposer de son URL. 

Par exemple: 
- AWS S3 : http://s3.amazonaws.com/  - qui est très souvent configuré par défaut, autant pour les librairies que pour les clients. 
- SSP CLOUD : https://minio.lab.sspcloud.fr
- LS3 : minio.datascience.kube.insee.fr
- pour un usage interne : minio.dev.kube.insee.fr
...

### Authentification

Ces APIs étant généralement sécurisées, il faudra des informations d'authentification (credentials) pour communiquer avec l'API afin qu'elle sache qui vous êtes et ce qu'il vous est permis de faire. Ainsi, nous disposeront d'une *access key*, d'une *secret key* ainsi que d'un jeton de session ou *token* utilisé dans le cadre d’une authentification temporaire.

Pourront être utilisées les variables d'environnements suivantes: elles sont généralement reconnus par les librairies

AWS_ACCESS_KEY_ID=my_access_key
AWS_SECRET_ACCESS_KEY=my_secret_key
AWS_SESSION_TOKEN = my_session_token
ENDPOINT_URL = s3_endpoint

Pour récupérer vos credentials, vous pouvez vous rendre sur 
- LS3 / SSPCLOUD : onglet my account > Connect to storage et sélectionner `shell environment variable`

## Un client pour communiquer avec S3

Afin de simplifier les intéractions avec l'API S3, nous allons utiliser un client s3. Cela permettra de gérer l'authentification de manière automatique. Il nous permettra également d'automatiser des transferts de fichiers, de naviguer facilement dans les buckets en ligne de commande.

Des exemples de clients s3:
- mc (Minio Client) : compatible pour tout service compatible s3
- s3cmd
- aws cli : outil officiel pour intéragir avec Amazon S3

Pour configurer mc : une variable d'environnement suffit : MC_HOST_ALIAS = "https://<Access Key>:<Secret Key>:<Session Token>@<YOUR-S3-ENDPOINT>"
exemple:
```
export MC_HOST_s3 = "https://$AWS_ACCESS_KEY_ID$:AWS_SECRET_ACCESS_KEY:AWS_SESSION_TOKEN@$ENDPOINT_URL$"
```

Une fois le tout configuré, nous pouvons lister le contenu de notre bucket
```
mc ls s3/my-bucket
```
copier un fichier
```
mc cp s3/my-bucket/my-file.txt s3/my-bucket/somewhere-else/my-file.txt
```
le télécharger
```
mc get s3/my-bucket/my-file.txt ./data/my-file.txt
```
le supprimer
```
mc rm s3/my-bucket/my-file.txt
```
le téléverser
```
mc put ./data/my-file.txt s3/my-bucket/my-second-file.txt
```

Définir un lien d'accès à un fichier

La commande `mc share download` génère une URL pré-signée contenant les identifiants d'accès intégrés, permettant de télécharger des objets depuis un bucket.

```
mc share download --expire DURATION ALIAS/PATH
```

## Service account

Au delà de votre compte personnel, vous avez la possibilité de créer un compte de service ou *service account*. A la différence de votre compte personnel, les credentials du service account seront permanents. Vous ne disposerez donc pas d'un session token, seulement d'une access key et secret key. Les services account sont généralement utilisés par des applications ou scripts pour accéder aux ressources s3.

Pour créer un  compte de service, c'est à dire une paire *access-key* *secret-key* : 

```
mc admin accesskey create        \
   s3/ myuser               \
   --access-key myuseraccesskey  \
   --secret-key myusersecretkey  \
```
NB : Anciennement on utilisait `mc admin user svcacct add` mais cette façon de faire est désormais dépréciée.

⚠️ le service account sera créé avec vos droits actuels, si vous souhaitez une gestion plus fine (accès sur un certain dossier, en lecture seulement...), il vous sera possible de définir une policy (fichier JSON qui déclare qui peut agir, sur quoi on peut agir et quelles actions sont effectuables). Pour les plus curieux, [nous renverrons à la documentation de minio](https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy-create.html)

Ainsi, si vous écrivez un script ou un service qui accède souvent à S3, utilisez un service account avec des clés gérées proprement (seulement les droits nécessaires, stockées de façon sécurisée...). En revanche, si vous voulez accéder à s3 de façon intéractive, utilisez des clés temporaires avec un session token.


# Duckdb 🦆

## Installation

Pour instaler duckdb, il n'y a rien de plus simple que se rendre sur [leur site documentaire](https://duckdb.org/docs/installation/?version=stable&environment=cli&platform=linux&download_method=direct&architecture=x86_64) et sélectionner notre cas d'usage : en l'occurence en ligne de commande.

## Configuration 

Pour configurer la cli vous avez la possibilité de créer un fichier `.duckdbrc` à la racine de votre répertoire personnel ($HOME). Ce fichier vous permettra d'exécuter du code au lancement de votre session duckdb.

```
.prompt 'duckdb>'
CREATE OR REPLACE SECRET secret ( TYPE s3, PROVIDER credential_chain, CHAIN "env;config", PROFILE 'default',  ENDPOINT "minio.lab.sspcloud.fr" );
```

## Première utilisation

in memory avec un fichier local 

Tips 
.once 
.timer on 


Lire un fichier parquet 
parquet c'est quoi ? 

Blob syntax pour lire plusieurs fichiers 
des requêtes : filtre sur des colonnes -> c'est rapide




::: {.cell .markdown}

<details>
<summary>Afficher la solution</summary>

Une solution

</details>

:::
